version: "3.9"

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "3456:8000"
    environment:
      - MONGODB_HOST_STRING=$MONGODB_HOST_STRING
