# Generated by Django 3.2.13 on 2022-05-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('campaign_url', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('total_records', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
