# Generated by Django 3.2.14 on 2022-08-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('an_ac_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='boost_count',
            field=models.IntegerField(default=0),
        ),
    ]
