# Generated by Django 3.2.15 on 2022-08-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('an_ac_stats', '0002_campaign_boost_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('campaigns', models.ManyToManyField(to='an_ac_stats.Campaign')),
            ],
        ),
    ]
