# Generated by Django 3.2.13 on 2022-05-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtable_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='api_key_name',
            field=models.CharField(default='AIRTABLE_API_KEY', max_length=100),
        ),
    ]
