# Generated by Django 3.2.13 on 2022-05-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airtable_generator', '0004_config_button_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='button_classes',
        ),
    ]
