# Generated by Django 3.2.13 on 2022-07-28 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirtableSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=50)),
                ('table', models.CharField(max_length=50)),
                ('view', models.CharField(max_length=50)),
                ('field_title', models.CharField(max_length=50)),
                ('field_start_time', models.CharField(max_length=50)),
                ('field_end_time', models.CharField(max_length=50, null=True)),
                ('field_browser_url', models.CharField(max_length=50)),
                ('field_latitude', models.CharField(max_length=50, null=True)),
                ('field_longitude', models.CharField(max_length=50, null=True)),
                ('field_online', models.CharField(max_length=50, null=True)),
                ('field_address', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventMap',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('sources_airtable', models.ManyToManyField(to='event_map.AirtableSync')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('browser_url', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('online', models.BooleanField()),
                ('address', models.CharField(max_length=200)),
                ('airtable_sync', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_map.airtablesync')),
            ],
        ),
    ]
