# Generated by Django 3.2.13 on 2022-07-28 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtablesync',
            name='field_last_modified',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airtablesync',
            name='last_synced',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='airtable_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='EventMap',
        ),
    ]
