# Generated by Django 3.2.13 on 2022-07-28 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0002_auto_20220728_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('airtable_syncs', models.ManyToManyField(to='event_map.AirtableSync')),
            ],
        ),
    ]
