# Generated by Django 3.2.13 on 2022-07-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0003_eventmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtablesync',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
