# Generated by Django 3.2.13 on 2022-07-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0004_airtablesync_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmap',
            name='name',
            field=models.CharField(default='Defund Climate Chaos', max_length=100),
            preserve_default=False,
        ),
    ]
