# Generated by Django 3.2.13 on 2022-07-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0005_eventmap_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtablesync',
            name='name',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
    ]
