# Generated by Django 3.2.14 on 2022-07-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0006_alter_airtablesync_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airtablesync',
            old_name='field_end_time',
            new_name='field_end_date',
        ),
        migrations.RenameField(
            model_name='airtablesync',
            old_name='field_start_time',
            new_name='field_start_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
