# Generated by Django 3.2.14 on 2022-07-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0007_auto_20220728_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_maps',
            field=models.ManyToManyField(to='event_map.EventMap'),
        ),
    ]
