# Generated by Django 3.2.14 on 2022-07-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0008_event_event_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(default='public', max_length=200),
            preserve_default=False,
        ),
    ]
