# Generated by Django 3.2.14 on 2022-07-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0009_event_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtablesync',
            name='field_visibility',
            field=models.CharField(default='Visibility', max_length=200),
        ),
    ]
