# Generated by Django 3.2.14 on 2022-07-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0010_airtablesync_field_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtablesync',
            name='field_summary',
            field=models.CharField(default='Summary', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
