# Generated by Django 3.2.14 on 2022-07-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0011_auto_20220728_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtablesync',
            name='field_summary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
