# Generated by Django 3.2.14 on 2022-07-29 00:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0012_alter_airtablesync_field_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionNetworkECSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('api_key', models.CharField(max_length=200)),
                ('event_campaign_api', models.CharField(max_length=200)),
                ('last_synced', models.DateTimeField(default=datetime.datetime(2022, 7, 29, 0, 34, 45, 453885, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='airtablesync',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='action_network_api',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='action_network_ec_sync',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_map.actionnetworkecsync'),
        ),
    ]
