# Generated by Django 3.2.14 on 2022-07-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0014_alter_actionnetworkecsync_last_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmap',
            name='action_network_ec_syncs',
            field=models.ManyToManyField(to='event_map.ActionNetworkECSync'),
        ),
    ]
