# Generated by Django 3.2.14 on 2022-08-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0017_auto_20220802_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
