# Generated by Django 3.2.14 on 2022-08-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0018_alter_event_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
