# Generated by Django 3.2.14 on 2022-08-10 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0019_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 20, 41, 4, 179912, tzinfo=utc)),
        ),
    ]
