# Generated by Django 3.2.14 on 2022-08-10 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event_map', '0020_event_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
